;!knitout-2
;;Carriers: 6

inhook 6
tuck - f41 6
tuck - b40 6
tuck - f39 6
tuck - b38 6
tuck - f37 6
tuck - b36 6
tuck - f35 6
tuck - b34 6
tuck - f33 6
tuck - b32 6
tuck - f31 6
tuck - b30 6
tuck - f29 6
tuck - b28 6
tuck - f27 6
tuck - b26 6
tuck - f25 6
tuck - b24 6
tuck - f23 6
tuck - b22 6
tuck - f21 6
tuck - b20 6
tuck - f19 6
tuck - b18 6
tuck - f17 6
tuck - b16 6
tuck - f15 6
tuck - b14 6
tuck - f13 6
tuck - b12 6
tuck - f11 6
tuck - b10 6
tuck - f9 6
tuck - b8 6
tuck - f7 6
tuck - b6 6
tuck - f5 6
tuck - b4 6
tuck - f3 6
tuck - b2 6
tuck - f1 6
knit + b2 6
knit + f3 6
knit + b4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + b8 6
knit + f9 6
knit + b10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + b14 6
knit + f15 6
knit + b16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + b20 6
knit + f21 6
knit + b22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + b26 6
knit + f27 6
knit + b28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + b32 6
knit + f33 6
knit + b34 6
knit + f35 6
knit + b36 6
knit + f37 6
knit + b38 6
knit + f39 6
knit + b40 6
knit + f41 6
releasehook 6
;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - b23 6 ;random
knit - b22 6 ;random
knit - f21 6 ;random
knit - b20 6 ;random
knit - b19 6 ;random
knit - b18 6 ;random
knit - b17 6 ;random
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6 ;random
knit + b18 6 ;random
knit + b19 6 ;random
knit + b20 6 ;random
knit + f21 6 ;random
knit + b22 6 ;random
knit + b23 6 ;random
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - b25 6 ;random
knit - f24 6 ;random
knit - f23 6 ;random
knit - f22 6 ;random
knit - f21 6 ;random
knit - f20 6 ;random
knit - f19 6 ;random
knit - f18 6 ;random
knit - f17 6 ;random
knit - b16 6 ;random
knit - b15 6 ;random
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6 ;random
knit + b16 6 ;random
knit + f17 6 ;random
knit + f18 6 ;random
knit + f19 6 ;random
knit + f20 6 ;random
knit + f21 6 ;random
knit + f22 6 ;random
knit + f23 6 ;random
knit + f24 6 ;random
knit + b25 6 ;random
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6 ;random
knit - b24 6 ;random
knit - b23 6 ;random
knit - f22 6 ;random
knit - b21 6 ;random
knit - b20 6 ;random
knit - f19 6 ;random
knit - f18 6 ;random
knit - f17 6 ;random
knit - f16 6 ;random
knit - b15 6 ;random
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6 ;random
knit + f16 6 ;random
knit + f17 6 ;random
knit + f18 6 ;random
knit + f19 6 ;random
knit + b20 6 ;random
knit + b21 6 ;random
knit + f22 6 ;random
knit + b23 6 ;random
knit + b24 6 ;random
knit + f25 6 ;random
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - b25 6 ;random
knit - b24 6 ;random
knit - f23 6 ;random
knit - f22 6 ;random
knit - b21 6 ;random
knit - b20 6 ;random
knit - f19 6 ;random
knit - f18 6 ;random
knit - f17 6 ;random
knit - f16 6 ;random
knit - f15 6 ;random
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + f15 6 ;random
knit + f16 6 ;random
knit + f17 6 ;random
knit + f18 6 ;random
knit + f19 6 ;random
knit + b20 6 ;random
knit + b21 6 ;random
knit + f22 6 ;random
knit + f23 6 ;random
knit + b24 6 ;random
knit + b25 6 ;random
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - b25 6 ;random
knit - f24 6 ;random
knit - f23 6 ;random
knit - b22 6 ;random
knit - b21 6 ;random
knit - f20 6 ;random
knit - b19 6 ;random
knit - f18 6 ;random
knit - f17 6 ;random
knit - b16 6 ;random
knit - b15 6 ;random
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6 ;random
knit + b16 6 ;random
knit + f17 6 ;random
knit + f18 6 ;random
knit + b19 6 ;random
knit + f20 6 ;random
knit + b21 6 ;random
knit + b22 6 ;random
knit + f23 6 ;random
knit + f24 6 ;random
knit + b25 6 ;random
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - b23 6 ;random
knit - b22 6 ;random
knit - b21 6 ;random
knit - b20 6 ;random
knit - b19 6 ;random
knit - f18 6 ;random
knit - f17 6 ;random
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + f17 6 ;random
knit + f18 6 ;random
knit + b19 6 ;random
knit + b20 6 ;random
knit + b21 6 ;random
knit + b22 6 ;random
knit + b23 6 ;random
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

;<
knit - f41 6
knit - b40 6
knit - f39 6
knit - b38 6
knit - f37 6
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - b32 6
knit - f31 6
knit - b30 6
knit - f29 6
knit - b28 6
knit - f27 6
knit - b26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - b20 6
knit - f19 6
knit - b18 6
knit - f17 6
knit - b16 6
knit - f15 6
knit - b14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - b8 6
knit - f7 6
knit - b6 6
knit - f5 6
knit - b4 6
knit - f3 6
knit - b2 6
knit - f1 6
xfer f41 b41
xfer b40 f40
xfer f39 b39
xfer b38 f38
xfer f37 b37
xfer b36 f36
xfer f35 b35
xfer b34 f34
xfer f33 b33
xfer b32 f32
xfer f31 b31
xfer b30 f30
xfer f29 b29
xfer b28 f28
xfer f27 b27
xfer b26 f26
xfer f25 b25
xfer b24 f24
xfer f23 b23
xfer b22 f22
xfer f21 b21
xfer b20 f20
xfer f19 b19
xfer b18 f18
xfer f17 b17
xfer b16 f16
xfer f15 b15
xfer b14 f14
xfer f13 b13
xfer b12 f12
xfer f11 b11
xfer b10 f10
xfer f9 b9
xfer b8 f8
xfer f7 b7
xfer b6 f6
xfer f5 b5
xfer b4 f4
xfer f3 b3
xfer b2 f2
xfer f1 b1
;>
knit + b1 6
knit + f2 6
knit + b3 6
knit + f4 6
knit + b5 6
knit + f6 6
knit + b7 6
knit + f8 6
knit + b9 6
knit + f10 6
knit + b11 6
knit + f12 6
knit + b13 6
knit + f14 6
knit + b15 6
knit + f16 6
knit + b17 6
knit + f18 6
knit + b19 6
knit + f20 6
knit + b21 6
knit + f22 6
knit + b23 6
knit + f24 6
knit + b25 6
knit + f26 6
knit + b27 6
knit + f28 6
knit + b29 6
knit + f30 6
knit + b31 6
knit + f32 6
knit + b33 6
knit + f34 6
knit + b35 6
knit + f36 6
knit + b37 6
knit + f38 6
knit + b39 6
knit + f40 6
knit + b41 6
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8
xfer b9 f9
xfer f10 b10
xfer b11 f11
xfer f12 b12
xfer b13 f13
xfer f14 b14
xfer b15 f15
xfer f16 b16
xfer b17 f17
xfer f18 b18
xfer b19 f19
xfer f20 b20
xfer b21 f21
xfer f22 b22
xfer b23 f23
xfer f24 b24
xfer b25 f25
xfer f26 b26
xfer b27 f27
xfer f28 b28
xfer b29 f29
xfer f30 b30
xfer b31 f31
xfer f32 b32
xfer b33 f33
xfer f34 b34
xfer b35 f35
xfer f36 b36
xfer b37 f37
xfer f38 b38
xfer b39 f39
xfer f40 b40
xfer b41 f41

outhook 6
